spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:nhom40authdb}
    username: ${MYSQL_ROOT_USERNAME:root}
    password: ${MYSQL_ROOT_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        id:
          new_generator_mappings: true
      ddl-auto: true
  main:
    allow-circular-references: true
  cache:
    type: redis
    redis:
      time-to-live: 6000000
  redis:
    host: localhost
    port: 6379
  cloud:
    discovery:
      enabled: true
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      producer.key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topic:
      name: auth_topics


springdoc:
  api-docs:
    path: /auth/api-docs
  swagger-ui:
    path: /auth/swagger-ui.html

server:
  port: 8088
  servlet:
    context-path: /Nhom40KLTN

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

app:
  jwt:
    secret: khoa_luan_tot_nghiep_nhom40_octopus
    milliseconds: 604800
    header: Authorization

resilience4j:
  circuitbreaker:
    instances:
      service-java:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 4
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
  retry:
    instances:
      service-java:
        wait-duration: 2s
        max-attempts: 3
  ratelimiter:
    instances:
      service-java:
        register-health-indicator: false
        limit-for-period: 3
        limit-refresh-period: 10s
        timeout-duration: 90s

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost

