spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://db-mysql-sgp1-75876-do-user-12877679-0.b.db.ondigitalocean.com:25060/userdb?ssl-mode=REQUIRED
    username: ${MYSQL_USER}
    password: ${MYSQL_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        id:
          new_generator_mappings: true
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  main:
    allow-circular-references: true
  cache:
    type: redis
    redis:
      time-to-live: 600000
  redis:
    url: ${REDIS_API:rediss://${REDIS_USER}:${REDIS_PASS}@db-redis-sgp1-58343-do-user-12877679-0.b.db.ondigitalocean.com:${REDIS_PORT:25061}}
  cloud:
    discovery:
      enabled: true
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8088

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

app:
  jwt:
    secret: khoa_luan_tot_nghiep_nhom40_octopus
    milliseconds: 604800
    header: Authorization

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: ${EUREKA_HOST:localhost}

