spring:
  application:
    name: authService
  datasource:
    url: jdbc:mysql://localhost:3306/nhom40db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        id:
          new_generator_mappings: true
      ddl-auto: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka
server:
  port: 8080
  servlet:
    context-path: /Nhom40KLTN

