version: '3.9'

services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - kafka-network
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    ports:
      - '9092:9092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper
    networks:
      - kafka-network
  eureka:
    container_name: eureka
    image: eureka:${TAG:-local}
    build:
      context: ./eureka-service
      args: 
        BUILD_ID: ${BUILD_ID:-local}
      labels:
        core.build.id: ${BUILD_ID:-local}
        core.git.sha: ${BUILD_ID:-local}
    ports:
      - "8761:8761"
    networks:
      - service-network
  gateway:
    container_name: gateway
    image: gateway:${TAG:-local}
    build:
      context: ./gateway
      args: 
        BUILD_ID: ${BUILD_ID:-local}
      labels:
        core.build.id: ${BUILD_ID:-local}
        core.git.sha: ${BUILD_ID:-local}
    ports:
      - "80:80"
    depends_on:
      - eureka
    networks:
      - service-network
  auth:
    container_name: auth
    image: auth:${TAG:-local}
    build:
      context: ./auth-service
      args: 
        BUILD_ID: ${BUILD_ID:-local}
      labels:
        core.build.id: ${BUILD_ID:-local}
        core.git.sha: ${BUILD_ID:-local}
    ports:
      - "8088:8088"
    depends_on:
      - eureka
      - kafka
    networks:
      - service-network
      - kafka-network
  message:
    container_name: message
    image: message:${TAG:-local}
    build:
      context: ./message-service
      args: 
        BUILD_ID: ${BUILD_ID:-local}
      labels:
        core.build.id: ${BUILD_ID:-local}
        core.git.sha: ${BUILD_ID:-local}
    ports:
      - "3000:3000"
    depends_on:
      - eureka
      - kafka
    networks:
      - service-network
      - kafka-network
  mail:
    container_name: mail
    image: mail:${TAG:-local}
    build:
      context: ./mail-service
      args: 
        BUILD_ID: ${BUILD_ID:-local}
      labels:
        core.build.id: ${BUILD_ID:-local}
        core.git.sha: ${BUILD_ID:-local}
    ports:
      - "8082:8082"
    depends_on:
      - eureka
      - kafka
    networks:
      - kafka-network
      - service-network
networks:
  service-network:
    driver: bridge
  kafka-network:
    driver: bridge
