version: '3.9'

services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - kafka-network
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    ports:
      - '9092:9092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper
    networks:
      - kafka-network
  eureka:
    container_name: eureka
    image: hoangdh2001/eureka
    build:
      context: ./eureka-service
    ports:
      - "8761:8761"
    networks:
      - service-network
  gateway:
    container_name: gateway
    image: hoangdh2001/gateway
    build:
      context: ./gateway
    ports:
      - "80:80"
    depends_on:
      - eureka
    environment:
      - EUREKA_HOST=eureka
    networks:
      - service-network
  auth:
    container_name: auth
    image: hoangdh2001/auth
    build:
      context: ./auth-service
    ports:
      - "8088:8088"
    depends_on:
      - eureka
      - kafka
    networks:
      - service-network
      - kafka-network
    env_file:
      - ./auth-service/.env
    environment:
      - EUREKA_HOST=eureka
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
  message:
    container_name: message
    image: hoangdh2001/message
    build:
      context: ./message-service
    ports:
      - "3000:3000"
    depends_on:
      - eureka
      - kafka
    env_file:
      - ./message-service/.env
    environment:
      - EUREKA_HOST=eureka
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
    networks:
      - service-network
      - kafka-network
  mail:
    container_name: mail
    image: hoangdh2001/mail
    build:
      context: ./mail-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka
      - kafka
    environment:
      - EUREKA_HOST=eureka
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
    networks:
      - kafka-network
      - service-network
networks:
  service-network:
    driver: bridge
  kafka-network:
    driver: bridge
