version: '3.9'

services:
  eureka:
    container_name: eureka
    image: eureka:${TAG:-local}
    build:
      context: ./eureka-service
      args:
        BUILD_ID: ${BUILD_ID:-local}
      labels:
        core.build.id: ${BUILD_ID:-local}
        core.git.sha: ${BUILD_ID:-local}
    ports:
      - "8761:8761"
    networks:
      - service-network
  gateway:
    container_name: gateway
    image: gateway:${TAG:-local}
    build:
      context: ./gateway
      args:
        BUILD_ID: ${BUILD_ID:-local}
      labels:
        core.build.id: ${BUILD_ID:-local}
        core.git.sha: ${BUILD_ID:-local}
    ports:
      - "80:80"
    depends_on:
      - eureka
    networks:
      - service-network
  auth:
    container_name: auth
    image: auth:${TAG:-local}
    build:
      context: ./auth-service
      args:
        BUILD_ID: ${BUILD_ID:-local}
      labels:
        core.build.id: ${BUILD_ID:-local}
        core.git.sha: ${BUILD_ID:-local}
    ports:
      - "8088:8088"
    depends_on:
      - eureka
    networks:
      - service-network
  message:
    container_name: message
    image: message:${TAG:-local}
    build:
      context: ./message-service
      args:
        BUILD_ID: ${BUILD_ID:-local}
      labels:
        core.build.id: ${BUILD_ID:-local}
        core.git.sha: ${BUILD_ID:-local}
    ports:
      - "3000:3000"
    depends_on:
      - eureka
    networks:
      - service-network
  mail:
    container_name: mail
    image: mail:${TAG:-local}
    build:
      context: ./mail-service
      args:
        BUILD_ID: ${BUILD_ID:-local}
      labels:
        core.build.id: ${BUILD_ID:-local}
        core.git.sha: ${BUILD_ID:-local}
    ports:
      - "8082:8082"
    depends_on:
      - eureka
    networks:
      - service-network
  workspace:
    container_name: workspace
    image: workspace:${TAG:-local}
    build:
      context: ./workspace-service
      args:
        BUILD_ID: ${BUILD_ID:-local}
      labels:
        core.build.id: ${BUILD_ID:-local}
        core.git.sha: ${BUILD_ID:-local}
    ports:
      - "8081:8081"
    depends_on:
      - eureka
    networks:
      - service-network
networks:
  service-network:
    driver: bridge
