apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.gatewayDesc.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gateway
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      containers:
        - name: gateway
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.gatewayDesc.image }}"
          imagePullPolicy: {{ .Values.gatewayDesc.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            tcpSocket:
                port: 80
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 300
            periodSeconds: 30
          env:
            {{- include "eureka.envVars" . | nindent 10 }}
          resources:
            {{- toYaml .Values.gatewayDesc.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
