apiVersion: v1
kind: Service
metadata:
  name: mail-service
  labels:
    app.kubernetes.io/name: mail-service
spec:
  type: {{ .Values.mailDesc.serviceType }}
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: mail-service