apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-service
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.messageDesc.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: message-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: message-service
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      containers:
        - name: message-service
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.messageDesc.image }}"
          imagePullPolicy: {{ .Values.messageDesc.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            tcpSocket:
                port: 3000
            initialDelaySeconds: 5
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
          env:
            {{- include "eureka.envVars" . | nindent 10 }}
            {{- include "redis.envVars" . | nindent 10 }}
            {{- include "message.envVars" . | nindent 10 }}
            {{- include "kafka.envVars" . | nindent 10 }}
          resources:
            {{- toYaml .Values.messageDesc.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
