apiVersion: v1
kind: Service
metadata:
  name: message-service
  labels:
    app.kubernetes.io/name: message-service
spec:
  type: {{ .Values.messageDesc.serviceType }}
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: message
  selector:
    app.kubernetes.io/name: message-service