apiVersion: v1
kind: Service
metadata:
  name: storage-service
  labels:
    app.kubernetes.io/name: storage-service
spec:
  type: {{ .Values.storageDesc.serviceType }}
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: storage-service