apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace-service
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.workspaceDesc.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: workspace-service
    metadata:
      labels:
        app.kubernetes.io/name: workspace-service
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      containers:
        - name: workspace
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.workspaceDesc.image }}"
          imagePullPolicy: {{ .Values.workspaceDesc.pullPolicy }}
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            tcpSocket:
                port: 8081
          readinessProbe:
            tcpSocket:
              port: 8081
          env:
            {{- include "eureka.envVars" . | nindent 10 }}
            {{- include "redis.envVars" . | nindent 10 }}
            {{- include "auth.envVars" . | nindent 10 }}
            {{- include "kafka.envVars" . | nindent 10 }}
            {{- include "domain" . | nindent 10 }}
          resources:
            {{- toYaml .Values.workspaceDesc.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
