apiVersion: v1
kind: Service
metadata:
  name: workspace-service
  labels:
    app.kubernetes.io/name: workspace-service
spec:
  type: {{ .Values.workspaceDesc.serviceType }}
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: workspace-service