server:
  port: 80
  eureka:
    instance:
      hostname: localhost
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**, /api/users/**, /auth/**
        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/api/message/**, /message/**
    discovery:
      enabled: true
logging:
  level:
    root: info
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: info
    org.springframework.cloud.gateway.handler: trace

jwt:
  secret: khoa_luan_tot_nghiep_nhom40_octopus